# Generated by Django 3.2.4 on 2021-06-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0003_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.IntegerField(choices=[('0', 'Useless'), ('1', 'Creative'), ('2', 'Boring'), ('3', 'Frustration')], default=False),
        ),
    ]
