# Generated by Django 3.2.4 on 2021-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0004_alter_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='function',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='iconClass1',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='iconClass2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='Details', max_length=15),
        ),
    ]
