# Generated by Django 3.2.4 on 2021-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0010_auto_20210619_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Boring', 'Boring'), ('Legendary', 'Legendary')], default='Common', max_length=9),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.IntegerField(choices=[(0, 'Useless'), (1, 'Creative'), (2, 'Boring'), (3, 'Frustration')], default=False),
        ),
    ]
