# Generated by Django 3.2.4 on 2021-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0011_auto_20210620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(blank=True, to='boring.BoringUser'),
        ),
    ]
