# Generated by Django 3.2.4 on 2021-06-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0012_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hint_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='function',
            field=models.CharField(default='', max_length=50),
        ),
    ]
