# Generated by Django 3.2.4 on 2021-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0014_game_times_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='boringuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
