# Generated by Django 3.2.4 on 2021-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0015_boringuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='boringuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
