# Generated by Django 3.2.4 on 2021-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0016_boringuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Boring', 'Boring'), ('Legendary', 'Legendary'), ('Comic', 'Comic Item')], default='Common', max_length=9),
        ),
    ]
