# Generated by Django 3.2.4 on 2021-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0017_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='function',
            field=models.CharField(choices=[('loveTheLogo', 'Love The Logo'), ('colorGame', 'colorGame'), ('seconds_game', 'Seconds Game'), ('no_you_cant_win', 'No you cant win.'), ('boring_switch', 'Boring Switch'), ('rgba_game', 'RGBA Game'), ('ninja', 'Ninja'), ('mysterious_messages', 'Mysterious Messages'), ('logo_click', 'Logo Click'), ('mysterious_emoji', 'Mysterious Emoji'), ('boring_rain', 'Boring Rain'), ('game_loading', 'Game Loading')], max_length=50),
        ),
    ]
