# Generated by Django 3.2.4 on 2021-07-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0003_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('CL', 'Clarity'), ('AC', 'Accuracy'), ('PR', 'Precision'), ('CM', 'Complexity'), ('AM', 'Amplitude'), ('LO', 'Logic'), ('MF', 'Meaningfullness'), ('OG', 'Originality')], default='OG', max_length=2)),
                ('grade', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boring_website.review')),
            ],
        ),
    ]
