# Generated by Django 3.2.4 on 2021-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0004_review_reviewelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbox',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
