# Generated by Django 3.2.4 on 2021-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0005_alter_contactbox_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='contactbox',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
