# Generated by Django 3.2.4 on 2021-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0007_rename_comments_reviewelement_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BooleanField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
