# Generated by Django 3.2.4 on 2021-07-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0008_quizzsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='boring_website.question'),
        ),
        migrations.AlterField(
            model_name='reviewelement',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='boring_website.review'),
        ),
    ]
