# Generated by Django 3.2.4 on 2021-07-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0012_auto_20210704_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_submissions', to='boring_website.questionsubmission'),
        ),
    ]
