# Generated by Django 3.2.4 on 2021-07-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0013_alter_answersubmission_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersubmission',
            name='question',
        ),
        migrations.AddField(
            model_name='answersubmission',
            name='question_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='boring_website.questionsubmission'),
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to='boring_website.question'),
        ),
    ]
