# Generated by Django 3.2.5 on 2021-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0014_auto_20210704_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzsubmission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
