# Generated by Django 3.2.5 on 2021-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_website', '0015_alter_quizzsubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzsubmission',
            name='final_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
